### ISSUE TITLE
Missing strings in translation

### ISSUE THREAD

**Issue by VasilisKos** [butzist/ActivityLauncher#186]
Looks like the terms "Settings" and "About" in the app settings are not included in the crowdin page, thus can't be translated. 
![Screenshot_20221231-154535-picsay](https://user-images.githubusercontent.com/12777771/210137403-023433ef-fce2-4bd8-ad79-dd1a2b9ec820.png)

**Comment by drogga** [comment]
@Ismael034 Isn't this already resolved \ fixed by you in the latest merged PR #189, can it be closed now ?

**Comment by VasilisKos** [comment]
The term "About" is still not available for translation. Just saying...

**Comment by butzist** [comment]
Any other strings that are missing, or just "About"?

**Comment by VasilisKos** [comment]
> Any other strings that are missing, or just "About"?

No. It was those two, as I mentioned in my initial message.

**Comment by butzist** [comment]
Updated strings.xml and "About" was indeed missing, "Settings" was already in there
